apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-deployment
spec:
  selector:
    matchLabels:
      app: hpa-deployment
  template:
    metadata:
      labels:
        app: hpa-deployment
    spec:
      containers:
      - name: hpa-deployment
        image: registry.k8s.io/hpa-example
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"   # 250m = 0.25 CPU cores
          limits:
            memory: "128Mi"
            cpu: "500m"   # 0.5 CPU cores
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: hpa-deployment
spec:
  selector:
    app: hpa-deployment
  ports:
  - port: 80
    targetPort: 80

