apiVersion: v1
kind: Pod
metadata:
  name: preff-pod
  labels:
    app.kubernetes.io/name: preff-pod
spec:
  containers:
  - name: preff-pod
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: Disktype
            operator: In
            values:
            - hemal