apiVersion: v1
kind: Pod
metadata:
  name: tcp-liveness
  labels:
    app.kubernetes.io/name: tcp-liveness
spec:
  containers:
  - name: tcp-liveness
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
