apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    env: demo
spec:
  type: NodePort 
  selector:
    app: nginx-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
