apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    env: demo
spec:
  replicas: 3
  selector:
    app: my-rc
  template:
    metadata:
      name: my-rc
      labels:
        app: my-rc
    spec:
      containers:
        - name: my-rc
          image: nginx:latest
          ports:
            - containerPort: 80


