apiVersion: v1
kind: Pod
metadata:
  name: tainted-pods
  labels:
    app.kubernetes.io/name: tainted-pods
spec:
  containers:
  - name: tainted-pods
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"