apiVersion: v1
kind: Pod
metadata:
  name: selectr-pod
  labels:
    app.kubernetes.io/name: selectr-pod
spec:
  containers:
  - name: selectr-pod
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  nodeSelector:
    gpu: "false"